package ArduinoML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum LCDBUS {
  BUS1("BUS1", "2, 3, 4, 5, 6, 7, 8"),
  BUS2("BUS2", "10, 11, 12, 13, 14, 15, 16"),
  BUS3("BUS3", "12, 11, 5, 4, 3, 2");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private LCDBUS(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<LCDBUS> getConstants() {
    List<LCDBUS> list = ListSequence.fromList(new LinkedList<LCDBUS>());
    ListSequence.fromList(list).addElement(LCDBUS.BUS1);
    ListSequence.fromList(list).addElement(LCDBUS.BUS2);
    ListSequence.fromList(list).addElement(LCDBUS.BUS3);
    return list;
  }
  public static LCDBUS getDefault() {
    return null;
  }
  public static LCDBUS parseValue(String value) {
    if (value == null) {
      return LCDBUS.getDefault();
    }
    if (value.equals(LCDBUS.BUS1.getValueAsString())) {
      return LCDBUS.BUS1;
    }
    if (value.equals(LCDBUS.BUS2.getValueAsString())) {
      return LCDBUS.BUS2;
    }
    if (value.equals(LCDBUS.BUS3.getValueAsString())) {
      return LCDBUS.BUS3;
    }
    return LCDBUS.getDefault();
  }
}
