package ArduinoML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum STATUS {
  high("high", true),
  low("low", false);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final boolean myValue;
  STATUS(String name, boolean value) {
    myName = name;
    myValue = value;
  }
  public boolean getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Boolean.toString(myValue);
  }
  public static List<STATUS> getConstants() {
    List<STATUS> list = ListSequence.fromList(new LinkedList<STATUS>());
    ListSequence.fromList(list).addElement(STATUS.high);
    ListSequence.fromList(list).addElement(STATUS.low);
    return list;
  }
  public static STATUS getDefault() {
    return null;
  }
  public static STATUS parseValue(String value) {
    if (value == null) {
      return STATUS.getDefault();
    }
    if (value.equals(STATUS.high.getValueAsString())) {
      return STATUS.high;
    }
    if (value.equals(STATUS.low.getValueAsString())) {
      return STATUS.low;
    }
    return STATUS.getDefault();
  }
}
